import pygame

# Window
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = 'Mechanics Simulator'
UI_COLOUR_BACKGROUND = 'white'

# Fps
FPS_INITIAL_CAP = 0
FPS_STEP = 60
FPS_MAX = 240

# Scale defaults
METRICS_SCALE_ZOOM_DEFAULT = 88
METRICS_SCALE_ZOOM_MIN = 2
METRICS_SCALE_ZOOM_MAX = 750

# Input / controls
MOUSE_PRIMARY_BUTTON = 1
KEY_TOGGLE_QUADTREE_BOUNDS = pygame.K_q
KEY_TOGGLE_COLLISION_MODE = pygame.K_c
KEY_CYCLE_FPS_CAP = pygame.K_f
KEY_QUIT = pygame.K_ESCAPE

# UI text
UI_TEXT_FORCES = 'Forces'
UI_TEXT_MASS = 'Mass'
UI_TEXT_RADIUS = 'Radius'
UI_TEXT_POSITION = 'Position'
UI_TEXT_VELOCITY = 'Velocity'
UI_TEXT_ACCELERATION = 'Acceleration'
UI_TEXT_START = 'Start'
UI_TEXT_END = 'End'
UI_TEXT_THICKNESS = 'Thickness'
UI_TEXT_RESTITUTION = 'Restitution'
UI_TEXT_GRAVITY = 'g'
UI_TEXT_SCALE = 'Scale: 1m'
UI_TEXT_COLLISION_SUFFIX = 'collisions'
UI_TEXT_PREMADE_WORLD_PREFIX = 'Premade'

TIME_FIELD_NAME = 'Time'

# UI colours
# Bottom panel input boxes
UI_COLOUR_BOTTOM_PANEL_INPUT_BOX = 'grey'
UI_COLOUR_BOTTOM_PANEL_INPUT_TEXT = 'black'
UI_COLOUR_BOTTOM_PANEL_INPUT_LABEL = 'white'
UI_COLOUR_BOTTOM_PANEL_INPUT_ACTIVE = 'white'

# Other panel input boxes (right/top/time etc.)
UI_COLOUR_PANEL_INPUT_BOX = 'grey'
UI_COLOUR_PANEL_INPUT_TEXT = 'black'
UI_COLOUR_PANEL_INPUT_LABEL = 'white'

UI_COLOUR_PANEL_INPUT_ACTIVE = 'white'
UI_COLOUR_TIME_ACTIVE = 'darkgreen'

UI_COLOUR_FORCE_ADDER_ICON = 'green'
UI_COLOUR_FORCE_WINDOW = 'cadetblue4'

UI_COLOUR_PANEL_BG = (50, 50, 50, 220)

UI_COLOUR_PANEL_PARTICLE = 'darkred'
UI_COLOUR_PANEL_ROD_PARTICLE = 'darkred'
UI_COLOUR_PANEL_ROD = 'darkblue'
UI_COLOUR_PANEL_PLANE = 'darkorchid4'

# UI palette for spawned body base colours
COLOURS: list[str] = [
    'aquamarine4',
    'blue3',
    'blueviolet',
    'chartreuse4',
    'crimson',
    'darkblue',
    'deeppink3',
    'indigo',
    'khaki4',
    'lightgoldenrod4',
    'lightslateblue',
    'tan3',
    'violetred4'
]

# UI layout ratios / offsets / drawing constants
LEFT_PANEL_START_X = 5
LEFT_PANEL_START_Y = 5
LEFT_PANEL_WIDTH_RATIO = 0.1
LEFT_PANEL_HEIGHT_RATIO = 0.35

BOTTOM_PANEL_TOP_RATIO = 0.8
BOTTOM_PANEL_Y_OFFSET = 15
BOTTOM_PANEL_HEIGHT_RATIO = 0.21

RIGHT_PANEL_START_X_RATIO = 0.875
RIGHT_PANEL_START_Y_RATIO = 0.125
RIGHT_PANEL_WIDTH_RATIO = 0.12
RIGHT_PANEL_HEIGHT_RATIO = 0.17
RIGHT_BOTTOM_PANEL_Y_MULTIPLIER = 2.5
RIGHT_TOP_PANEL_G_Y_RATIO = 0.25
RIGHT_TOP_PANEL_E_Y_RATIO = 2 / 3

INPUT_BOX_WIDTH_RATIO = 0.1
INPUT_BOX_HEIGHT_RATIO = 0.03
INPUT_BOX_X_DIVISOR = 6
INPUT_BOX_Y_OFFSET = 15
INPUT_BOX_VERTICAL_GAP_RATIO = 1.1

FORCE_WINDOW_X_OFFSET = 0.016
FORCE_WINDOW_Y_OFFSET = 0.03
FORCE_WINDOW_WIDTH_OFFSET = 0.02
FORCE_WINDOW_HEIGHT_RATIO = 0.21

BOTTOM_PANEL_FIELD_X_STEP_1 = 1 / 6
BOTTOM_PANEL_FIELD_X_STEP_2 = 1 / 3
BOTTOM_PANEL_FIELD_X_STEP_3 = 1 / 2
BOTTOM_PANEL_FIELD_X_STEP_4 = 2 / 3

LEFT_PANEL_WIDGET_X_CENTER = 0.5
LEFT_PANEL_WIDGET_Y_PARTICLE = 0.25
LEFT_PANEL_WIDGET_Y_ROD = 0.5
LEFT_PANEL_WIDGET_Y_PLANE = 0.75
LEFT_PANEL_ICON_RADIUS_X_FACTOR = 0.9
LEFT_PANEL_ICON_RADIUS_Y_FACTOR = 0.6
LEFT_PANEL_PARTICLE_RADIUS_RATIO = 0.0417
LEFT_PANEL_ROD_PARTICLE_RADIUS_RATIO = 0.008
LEFT_PANEL_PLANE_THICKNESS_RATIO = 0.01
LEFT_PANEL_MIN_THICKNESS_PX = 1
NEW_PARTICLE_RADIUS = 0.1
NEW_ROD_LENGTH_RATIO = 0.0003
NEW_PLANE_LENGTH_RATIO = 0.002

PANEL_CORNER_RADIUS = 15
INPUT_BOX_CORNER_RADIUS = 7
INPUT_BOX_SIDE_LABEL_Y_OFFSET_RATIO = 0.07
INPUT_BOX_DELETE_X_SCALE = 0.98
INPUT_BOX_DELETE_Y_OFFSET_RATIO = 0.25
INPUT_BOX_DELETE_SIZE_RATIO = 0.5
INPUT_BOX_ICON_LINE_THICKNESS = 2

FORCE_WINDOW_CORNER_RADIUS = 5
FORCE_WINDOW_BOX_X_DIVISOR = 1.15
FORCE_WINDOW_X_COMPONENT_Y_SCALE = 1.01
FORCE_WINDOW_COMPONENT_GAP_SCALE = 1.1
FORCE_WINDOW_ROW_GAP_SCALE = 2.4
FORCE_WINDOW_ADDER_H_START_SCALE = 1.005
FORCE_WINDOW_ADDER_H_END_SCALE = 1.025
FORCE_WINDOW_ADDER_V_X_SCALE = 1.015
FORCE_WINDOW_ADDER_V_Y_START_DIVISOR = 12
FORCE_WINDOW_LABEL_Y_SCALE = 0.97
FORCE_WINDOW_LABEL_HEIGHT_RATIO = 0.03
FORCE_WINDOW_ICON_THICKNESS = 2
FORCE_WINDOW_SCROLL_STEP = 10

PANEL_ROD_THICKNESS_SCALE = 0.6
PANEL_ROD_MIN_THICKNESS = 1

METRICS_FONT_HEIGHT_RATIO = 0.03
METRICS_FPS_POS_X_RATIO = 0.97
METRICS_FPS_POS_Y_RATIO = 0.02
METRICS_FPS_WIDTH_RATIO = 0.01
METRICS_FPS_HEIGHT_RATIO = 0.01
METRICS_SCALE_POS_X_RATIO = 0.99
METRICS_SCALE_POS_Y_RATIO = 0.05
METRICS_SCALE_TEXT_X_RATIO = 0.93
METRICS_SCALE_TEXT_Y_RATIO = 0.06
METRICS_SCALE_TIP_END_Y_RATIO = 0.9
METRICS_MODE_POS_X_RATIO = 0.875
METRICS_MODE_POS_Y_RATIO = 0.075
METRICS_MODE_WIDTH_RATIO = 0.12
METRICS_MODE_HEIGHT_RATIO = 0.035
METRICS_LINE_THICKNESS = 2
METRICS_SCALE_LABEL_MIN_WIDTH = 60

PLAY_BUTTON_WIDTH_RATIO = 0.021
PLAY_BUTTON_HEIGHT_RATIO = 0.03
PLAY_BUTTON_CENTER_X_RATIO = 0.5
DELETE_BUTTON_X_OFFSET_RATIO = 0.03
DELETE_BUTTON_Y_SCALE = 1.005
DELETE_BUTTON_WIDTH_SCALE = 0.6
DELETE_BUTTON_HEIGHT_SCALE = 0.8
TIME_CONTROL_X_SCALE = 0.8
TIME_CONTROL_WIDTH_SCALE = 0.95
DELETE_BUTTON_CROSS_THICKNESS = 3